"""GlowScript code generator.

Turns a natural-language description of a physics simulation into ready-to-run
GlowScript/VPython code by matching against the knowledge-base templates.
"""
from dataclasses import dataclass

from glowscript_agent.knowledge import TEMPLATES, get_template


@dataclass
class SimulationSpec:
    """A request to generate a simulation."""

    description: str
    template: str = "projectile"


def match_template(description: str) -> str:
    """Match a natural-language description to the best template name.

    Uses keyword matching against each template's keyword list. Falls back to
    'projectile' when nothing matches.
    """
    desc_lower = description.lower()
    best = "projectile"
    best_score = 0
    for name, tpl in TEMPLATES.items():
        score = sum(1 for kw in tpl["keywords"] if kw.lower() in desc_lower)
        if score > best_score:
            best_score = score
            best = name
    return best


def generate_simulation(spec: SimulationSpec) -> str:
    """Generate GlowScript code for the given simulation spec.

    Raises KeyError if the template name is unknown.
    """
    tpl = get_template(spec.template)
    header = (
        "# Generated by glowscript-agent\n"
        f"# Description: {spec.description}\n"
        "# Template: {0}\n".format(spec.template)
    )
    return header + "\n" + tpl["code"]
