// Generated by @syncular/typegen — DO NOT EDIT.
// irVersion: 1
// ⚠️ 이 파일은 SYNCULAR_DESIGN.md §4·§5 스키마를 생성 형식에 맞게 옮긴 것이다.
//    착수 단계 1에서 `syncular generate`를 실행하면 이 파일이 공식 생성본으로
//    교체된다 (syncular.json의 output.module 경로 = 이 파일).

/** Structural descriptor consumed by renderer bindings; phantom type
 * fields make row/insert/update/id inference available without imports. */
export interface SyncTable<Row, Insert, Update, Id> {
  readonly name: string;
  /** Language-facing key used in generated row and mutation types. */
  readonly primaryKey: keyof Row & string;
  /** Physical SQLite/wire primary-key column. */
  readonly physicalPrimaryKey: string;
  readonly __row?: Row;
  readonly __insert?: Insert;
  readonly __update?: Update;
  readonly __id?: Id;
}

/** ServerSchema-compatible schema object (SPEC §2.4, §3.1). */
export const schema = {
  version: 1,
  tables: [
    {
      name: 'posts',
      columns: [
        { name: 'id', type: 'string', nullable: false },
        { name: 'public_id', type: 'string', nullable: false },
        { name: 'author_id', type: 'string', nullable: false },
        { name: 'author_name', type: 'string', nullable: false },
        { name: 'author_avatar', type: 'string', nullable: false },
        { name: 'types', type: 'json', nullable: false },
        { name: 'mode', type: 'string', nullable: false },
        { name: 'region', type: 'string', nullable: false },
        { name: 'days', type: 'json', nullable: false },
        { name: 'time_slot', type: 'string', nullable: false },
        { name: 'capacity', type: 'integer', nullable: false },
        { name: 'intro', type: 'string', nullable: false },
        { name: 'deadline', type: 'string', nullable: false },
        { name: 'status', type: 'string', nullable: false },
        { name: 'updated_at_ms', type: 'integer', nullable: false },
      ],
      primaryKey: 'id',
      scopes: [
        { pattern: 'public:{public_id}', column: 'public_id' },
      ],
    },
    {
      name: 'feed_items',
      columns: [
        { name: 'id', type: 'string', nullable: false },
        { name: 'public_id', type: 'string', nullable: false },
        { name: 'user_id', type: 'string', nullable: false },
        { name: 'user_name', type: 'string', nullable: false },
        { name: 'avatar', type: 'string', nullable: false },
        { name: 'mission_title', type: 'string', nullable: false },
        { name: 'memo', type: 'string', nullable: false },
        { name: 'photo', type: 'blob_ref', nullable: true },
        { name: 'created_at_ms', type: 'integer', nullable: false },
      ],
      primaryKey: 'id',
      scopes: [
        { pattern: 'public:{public_id}', column: 'public_id' },
      ],
    },
    {
      name: 'cheers',
      columns: [
        { name: 'id', type: 'string', nullable: false },
        { name: 'public_id', type: 'string', nullable: false },
        { name: 'feed_id', type: 'string', nullable: false },
        { name: 'user_id', type: 'string', nullable: false },
        { name: 'cheer_type', type: 'string', nullable: false },
        { name: 'created_at_ms', type: 'integer', nullable: false },
      ],
      primaryKey: 'id',
      scopes: [
        { pattern: 'public:{public_id}', column: 'public_id' },
      ],
    },
    {
      name: 'user_profiles',
      columns: [
        { name: 'id', type: 'string', nullable: false },
        { name: 'public_id', type: 'string', nullable: false },
        { name: 'display_name', type: 'string', nullable: false },
        { name: 'avatar', type: 'string', nullable: false },
        { name: 'interests', type: 'json', nullable: false },
        { name: 'created_at_ms', type: 'integer', nullable: false },
        { name: 'updated_at_ms', type: 'integer', nullable: false },
      ],
      primaryKey: 'id',
      scopes: [
        { pattern: 'public:{public_id}', column: 'public_id' },
      ],
    },
    {
      name: 'applications',
      columns: [
        { name: 'id', type: 'string', nullable: false },
        { name: 'apply_scope', type: 'string', nullable: false },
        { name: 'post_id', type: 'string', nullable: false },
        { name: 'group_id', type: 'string', nullable: false },
        { name: 'applicant_id', type: 'string', nullable: false },
        { name: 'applicant_name', type: 'string', nullable: false },
        { name: 'applicant_avatar', type: 'string', nullable: false },
        { name: 'status', type: 'string', nullable: false },
        { name: 'message', type: 'string', nullable: false },
        { name: 'updated_at_ms', type: 'integer', nullable: false },
      ],
      primaryKey: 'id',
      scopes: [
        { pattern: 'apply:{apply_scope}', column: 'apply_scope' },
      ],
    },
    {
      name: 'group_members',
      columns: [
        { name: 'id', type: 'string', nullable: false },
        { name: 'group_id', type: 'string', nullable: false },
        { name: 'post_id', type: 'string', nullable: false },
        { name: 'user_id', type: 'string', nullable: false },
        { name: 'role', type: 'string', nullable: false },
        { name: 'joined_at_ms', type: 'integer', nullable: false },
      ],
      primaryKey: 'id',
      scopes: [
        { pattern: 'group:{group_id}', column: 'group_id' },
      ],
    },
    {
      name: 'verifications',
      columns: [
        { name: 'id', type: 'string', nullable: false },
        { name: 'verify_scope', type: 'string', nullable: false },
        { name: 'group_id', type: 'string', nullable: false },
        { name: 'user_id', type: 'string', nullable: false },
        { name: 'mission_id', type: 'string', nullable: false },
        { name: 'mission_title', type: 'string', nullable: false },
        { name: 'mission_kind', type: 'string', nullable: false },
        { name: 'date', type: 'string', nullable: false },
        { name: 'memo', type: 'string', nullable: false },
        { name: 'photo', type: 'blob_ref', nullable: true },
        { name: 'created_at_ms', type: 'integer', nullable: false },
      ],
      primaryKey: 'id',
      scopes: [
        { pattern: 'verify:{verify_scope}', column: 'verify_scope' },
      ],
    },
    {
      name: 'missions',
      columns: [
        { name: 'id', type: 'string', nullable: false },
        { name: 'user_id', type: 'string', nullable: false },
        { name: 'kind', type: 'string', nullable: false },
        { name: 'date', type: 'string', nullable: true },
        { name: 'week_key', type: 'string', nullable: true },
        { name: 'title', type: 'string', nullable: false },
        { name: 'goal', type: 'integer', nullable: false },
        { name: 'status', type: 'string', nullable: false },
        { name: 'verified_at_ms', type: 'integer', nullable: true },
        { name: 'updated_at_ms', type: 'integer', nullable: false },
      ],
      primaryKey: 'id',
      scopes: [
        { pattern: 'user:{user_id}', column: 'user_id' },
      ],
    },
    {
      name: 'point_ledger',
      columns: [
        { name: 'id', type: 'string', nullable: false },
        { name: 'user_id', type: 'string', nullable: false },
        { name: 'amount', type: 'integer', nullable: false },
        { name: 'reason', type: 'string', nullable: false },
        { name: 'balance_after', type: 'integer', nullable: false },
        { name: 'created_at_ms', type: 'integer', nullable: false },
      ],
      primaryKey: 'id',
      scopes: [
        { pattern: 'user:{user_id}', column: 'user_id' },
      ],
    },
    {
      name: 'streaks',
      columns: [
        { name: 'id', type: 'string', nullable: false },
        { name: 'user_id', type: 'string', nullable: false },
        { name: 'current', type: 'integer', nullable: false },
        { name: 'best', type: 'integer', nullable: false },
        { name: 'last_date', type: 'string', nullable: true },
        { name: 'lottery_used_week', type: 'string', nullable: true },
        { name: 'updated_at_ms', type: 'integer', nullable: false },
      ],
      primaryKey: 'id',
      scopes: [
        { pattern: 'user:{user_id}', column: 'user_id' },
      ],
    },
    {
      name: 'badges',
      columns: [
        { name: 'id', type: 'string', nullable: false },
        { name: 'user_id', type: 'string', nullable: false },
        { name: 'badge_id', type: 'string', nullable: false },
        { name: 'earned_at_ms', type: 'integer', nullable: false },
      ],
      primaryKey: 'id',
      scopes: [
        { pattern: 'user:{user_id}', column: 'user_id' },
      ],
    },
  ],
} as const;

/* ---------- 행 타입 (주요 테이블) ---------- */

export interface PostsRow {
  id: string;
  publicId: string;
  authorId: string;
  authorName: string;
  authorAvatar: string;
  types: unknown;
  mode: string;
  region: string;
  days: unknown;
  timeSlot: string;
  capacity: number;
  intro: string;
  deadline: string;
  status: string;
  updatedAtMs: number;
}

export interface FeedItemsRow {
  id: string;
  publicId: string;
  userId: string;
  userName: string;
  avatar: string;
  missionTitle: string;
  memo: string;
  photo: string | null;
  createdAtMs: number;
}

export interface VerificationsRow {
  id: string;
  verifyScope: string;
  groupId: string;
  userId: string;
  missionId: string;
  missionTitle: string;
  missionKind: string;
  date: string;
  memo: string;
  photo: string | null;
  createdAtMs: number;
}

export interface MissionsRow {
  id: string;
  userId: string;
  kind: string;
  date: string | null;
  weekKey: string | null;
  title: string;
  goal: number;
  status: string;
  verifiedAtMs: number | null;
  updatedAtMs: number;
}

/* ---------- 구독 템플릿 (SYNCULAR_DESIGN.md §5 subscriptions) ---------- */

/** Requested-scope template for the 'publicFeed' subscription. */
export const publicFeedSubscription = {
  name: 'publicFeed',
  table: 'feed_items',
  scopes: (): Record<string, string[]> => ({ public_id: ['main'] }),
} as const;

/** Requested-scope template for the 'allVerifs' subscription. */
export const allVerifsSubscription = {
  name: 'allVerifs',
  table: 'verifications',
  scopes: (): Record<string, string[]> => ({ verify_scope: ['live'] }),
} as const;

/** Requested-scope template for the 'myMissions' subscription. */
export const myMissionsSubscription = {
  name: 'myMissions',
  table: 'missions',
  scopes: (params: { actorId: string }): Record<string, string[]> => ({
    user_id: [params.actorId],
  }),
} as const;